-- Phase 13: verified tourism catalog for Manta.
-- Coordinates were checked against the linked OpenStreetMap objects on 2026-07-22.

with verified_existing(id, longitude, latitude, source_name, source_url) as (
  values
    ('10000000-0000-4000-8000-000000000001'::uuid, -80.7290206, -0.9374502, 'OpenStreetMap', 'https://www.openstreetmap.org/way/32500785'),
    ('10000000-0000-4000-8000-000000000002'::uuid, -80.7454361, -0.9436616, 'OpenStreetMap', 'https://www.openstreetmap.org/way/98351537'),
    ('10000000-0000-4000-8000-000000000003'::uuid, -80.8114091, -0.9556986, 'OpenStreetMap', 'https://www.openstreetmap.org/node/7933203950'),
    ('10000000-0000-4000-8000-000000000004'::uuid, -80.8472200, -0.9855600, 'Visit Manta', 'https://www.visitmanta.org/en/properties-2'),
    ('10000000-0000-4000-8000-000000000005'::uuid, -80.9068623, -1.0714337, 'OpenStreetMap', 'https://www.openstreetmap.org/way/411310410'),
    ('10000000-0000-4000-8000-000000000006'::uuid, -80.7304124, -0.9418757, 'OpenStreetMap', 'https://www.openstreetmap.org/way/411306196'),
    ('10000000-0000-4000-8000-000000000007'::uuid, -80.7216587, -0.9475894, 'OpenStreetMap', 'https://www.openstreetmap.org/way/848306795'),
    ('10000000-0000-4000-8000-000000000008'::uuid, -80.7323358, -0.9427418, 'OpenStreetMap', 'https://www.openstreetmap.org/way/411056993')
)
update public.places p
set location = extensions.st_setsrid(extensions.st_point(v.longitude, v.latitude), 4326)::extensions.geography,
    source_name = v.source_name,
    source_url = v.source_url,
    source_checked_at = '2026-07-22T00:00:00Z'::timestamptz,
    updated_at = now()
from verified_existing v
where p.id = v.id;

with place_data(
  id, category_slug, longitude, latitude, address, website_url, price_level,
  name_es, name_en, short_es, short_en, description_es, description_en, source_url
) as (
  values
    ('10000000-0000-4000-8000-000000000009'::uuid, 'playas', -80.7134880, -0.9499295, 'Sector Tarqui, Manta, Manabí', null, 0, 'Playa Tarqui', 'Tarqui Beach', 'Playa urbana vinculada a la tradición pesquera y gastronómica de Tarqui.', 'An urban beach connected with Tarqui’s fishing and culinary traditions.', 'Playa Tarqui recorre un sector histórico de la costa mantense. Su entorno permite observar la actividad marítima local y acercarse a mercados y espacios gastronómicos tradicionales.', 'Tarqui Beach extends along a historic part of Manta’s coast. Its surroundings offer a view of local maritime activity and access to traditional markets and food venues.', 'https://www.openstreetmap.org/way/32500818'),
    ('10000000-0000-4000-8000-000000000010'::uuid, 'playas', -80.7074535, -0.9499307, 'Sector Los Esteros, Manta, Manabí', null, 0, 'Playa Los Esteros', 'Los Esteros Beach', 'Costa urbana próxima al barrio Los Esteros y a su actividad pesquera.', 'Urban coastline beside Los Esteros and its fishing activity.', 'Playa Los Esteros forma parte del paisaje marítimo del este de Manta. Es un punto para conocer la relación cotidiana del barrio con la pesca, el comercio y el océano.', 'Los Esteros Beach is part of eastern Manta’s maritime landscape. It offers a close look at the neighborhood’s everyday relationship with fishing, trade, and the ocean.', 'https://www.openstreetmap.org/way/32686225'),
    ('10000000-0000-4000-8000-000000000011'::uuid, 'playas', -80.7934879, -0.9591055, 'Ruta del Spondylus, Piedra Larga, Manta, Manabí', null, 0, 'Playa Piedra Larga', 'Piedra Larga Beach', 'Pequeña playa y mirador costero en la vía occidental de Manta.', 'A small beach and coastal viewpoint on Manta’s western route.', 'Piedra Larga combina una franja de playa con vistas abiertas al Pacífico. El sector es conocido por sus atardeceres y por la oferta de restaurantes y espacios de encuentro cercanos.', 'Piedra Larga combines a narrow beach with open Pacific views. The area is known for sunsets and nearby restaurants and social spaces.', 'https://www.openstreetmap.org/way/572712711'),
    ('10000000-0000-4000-8000-000000000012'::uuid, 'playas', -80.8817004, -1.0252738, 'Ruta del Spondylus, Ligüiqui, Manta, Manabí', null, 0, 'Playa Ligüiqui', 'Ligüiqui Beach', 'Playa rural cercana a vestigios arqueológicos y corrales marinos ancestrales.', 'A rural beach near archaeological remains and ancestral marine corrals.', 'Ligüiqui ofrece un entorno costero tranquilo al sur del cantón. La visita puede complementarse con los corrales marinos y otros testimonios del conocimiento ancestral de sus comunidades.', 'Ligüiqui offers a quiet coastal setting in the south of the canton. A visit can be combined with the marine corrals and other evidence of ancestral community knowledge.', 'https://www.openstreetmap.org/way/858689574'),
    ('10000000-0000-4000-8000-000000000013'::uuid, 'museos', -80.7094925, -0.9512168, 'Avenida Puerto-Aeropuerto, Manta, Manabí', null, 0, 'Museo del Mar', 'Museum of the Sea', 'Espacio museístico dedicado a la relación de Manta con el océano.', 'A museum space devoted to Manta’s relationship with the ocean.', 'El Museo del Mar presenta la identidad marítima de Manta desde una ubicación cercana a la costa de Tarqui. Su temática ayuda a comprender la pesca, la navegación y la vida portuaria.', 'The Museum of the Sea presents Manta’s maritime identity from a location near the Tarqui coast. Its theme helps visitors understand fishing, navigation, and port life.', 'https://www.openstreetmap.org/way/1116599364'),
    ('10000000-0000-4000-8000-000000000014'::uuid, 'museos', -80.7211092, -0.9504676, 'Centro de Manta, Manabí', null, 0, 'Museo del Banco Central', 'Central Bank Museum', 'Punto cultural asociado a colecciones arqueológicas e históricas de Manabí.', 'A cultural venue associated with archaeological and historical collections from Manabí.', 'Este museo constituye una referencia cultural del centro de Manta. Sus colecciones permiten aproximarse a los pueblos prehispánicos y a distintos momentos de la historia regional.', 'This museum is a cultural reference point in central Manta. Its collections offer an introduction to pre-Hispanic peoples and different periods of regional history.', 'https://www.openstreetmap.org/node/367833596'),
    ('10000000-0000-4000-8000-000000000015'::uuid, 'parques', -80.7220102, -0.9468395, 'Avenida 2, centro de Manta, Manabí', null, 0, 'Parque Central', 'Central Park', 'Parque tradicional para descansar y recorrer el centro histórico de Manta.', 'A traditional park for resting and exploring Manta’s historic center.', 'El Parque Central funciona como espacio de encuentro ciudadano en el núcleo urbano. Desde allí se puede continuar a pie hacia plazas, iglesias, museos y comercios del centro.', 'Central Park is a civic meeting place in the urban core. From there, visitors can continue on foot to nearby squares, churches, museums, and shops.', 'https://www.openstreetmap.org/way/851730829'),
    ('10000000-0000-4000-8000-000000000016'::uuid, 'parques', -80.7186800, -0.9487070, 'Avenida Malecón, Manta, Manabí', null, 0, 'Megaparque Centenario Agustín Intriago', 'Agustín Intriago Centennial Park', 'Amplio parque urbano frente al mar con áreas recreativas y de paseo.', 'A large seafront urban park with recreation and walking areas.', 'El Megaparque Centenario ofrece espacios abiertos para caminar, descansar y compartir en familia. Su cercanía al litoral lo integra al circuito de plazas y malecones del este de la ciudad.', 'Centennial Park provides open areas for walking, resting, and family time. Its coastal location connects it with the plazas and boardwalks on the city’s eastern side.', 'https://www.openstreetmap.org/way/1304021660'),
    ('10000000-0000-4000-8000-000000000017'::uuid, 'parques', -80.7097902, -0.9513334, 'Sector Tarqui, Manta, Manabí', null, 0, 'Plaza del Mar', 'Sea Plaza', 'Plaza costera para caminar y observar el entorno marítimo de Tarqui.', 'A coastal plaza for walking and viewing Tarqui’s maritime setting.', 'Plaza del Mar es un espacio público próximo a la playa y al Museo del Mar. Su recorrido permite conectar la memoria pesquera del sector con nuevas áreas de paseo urbano.', 'Sea Plaza is a public space near the beach and the Museum of the Sea. Its paths connect the area’s fishing heritage with newer urban walking spaces.', 'https://www.openstreetmap.org/way/887947219'),
    ('10000000-0000-4000-8000-000000000018'::uuid, 'parques', -80.7219142, -0.9477754, 'Centro de Manta, Manabí', null, 0, 'Plazoleta Azúa', 'Azúa Square', 'Pequeña plaza urbana junto a hitos culturales del centro de Manta.', 'A small urban square beside cultural landmarks in central Manta.', 'La Plazoleta Azúa brinda una pausa durante los recorridos a pie por el centro. Su escala peatonal y cercanía al Museo Cancebí facilitan integrarla en una ruta cultural corta.', 'Azúa Square offers a pause during walking tours of central Manta. Its pedestrian scale and proximity to the Cancebí Museum make it easy to include in a short cultural route.', 'https://www.openstreetmap.org/way/856632542'),
    ('10000000-0000-4000-8000-000000000019'::uuid, 'monumentos', -80.7127487, -0.9534048, 'Tarqui, Manta, Manabí', null, 0, 'Memorial 16A', '16A Memorial', 'Memorial dedicado a las víctimas y a la resiliencia tras el terremoto de 2016.', 'A memorial to the victims and resilience shown after the 2016 earthquake.', 'El Memorial 16A conserva la memoria del terremoto que transformó Manta y Manabí. Es un espacio de reflexión sobre las pérdidas, la solidaridad y la reconstrucción de la ciudad.', 'The 16A Memorial preserves the memory of the earthquake that transformed Manta and Manabí. It is a place to reflect on loss, solidarity, and the city’s reconstruction.', 'https://www.openstreetmap.org/node/7932115609'),
    ('10000000-0000-4000-8000-000000000020'::uuid, 'monumentos', -80.7172591, -0.9524552, 'Avenida Malecón, Manta, Manabí', null, 0, 'Monumento Al Pescador', 'Fisherman Monument', 'Monumento que reconoce el oficio pesquero y la identidad marítima local.', 'A monument honoring fishing work and local maritime identity.', 'El Monumento Al Pescador rinde homenaje a una actividad fundamental para la historia y la economía de Manta. Su presencia en el litoral recuerda el trabajo cotidiano de generaciones de familias.', 'The Fisherman Monument honors an activity central to Manta’s history and economy. Its coastal setting recalls the daily work of generations of local families.', 'https://www.openstreetmap.org/node/4603037391'),
    ('10000000-0000-4000-8000-000000000021'::uuid, 'monumentos', -80.7221725, -0.9461954, 'Centro de Manta, Manabí', null, 0, 'Silla Ceremonial de Manta', 'Manta Ceremonial Seat', 'Escultura inspirada en las sillas de poder de la cultura manteña.', 'A sculpture inspired by the seats of power of the Manteño culture.', 'La Silla Ceremonial representa uno de los símbolos arqueológicos más reconocibles de la cultura manteña. La obra invita a relacionar la ciudad actual con su pasado prehispánico y navegante.', 'The Ceremonial Seat represents one of the most recognizable archaeological symbols of the Manteño culture. It connects today’s city with its pre-Hispanic and seafaring past.', 'https://www.openstreetmap.org/node/7986997365'),
    ('10000000-0000-4000-8000-000000000022'::uuid, 'monumentos', -80.7459544, -0.9547519, 'Parroquia Eloy Alfaro, Manta, Manabí', null, 0, 'Monumento Eloy Alfaro', 'Eloy Alfaro Monument', 'Monumento dedicado al líder liberal nacido en la provincia de Manabí.', 'A monument dedicated to the liberal leader born in Manabí Province.', 'El monumento recuerda la figura de Eloy Alfaro y su influencia en la historia republicana del Ecuador. También vincula la identidad manabita con los procesos de transformación nacional.', 'The monument recalls Eloy Alfaro and his influence on Ecuador’s republican history. It also links Manabí identity with the country’s major processes of change.', 'https://www.openstreetmap.org/way/859140110'),
    ('10000000-0000-4000-8000-000000000023'::uuid, 'monumentos', -80.9047900, -1.0713669, 'Malecón de San Lorenzo, Manta, Manabí', null, 0, 'Tortuga de San Lorenzo', 'San Lorenzo Turtle', 'Escultura costera que destaca la fauna marina del sector de San Lorenzo.', 'A coastal sculpture highlighting the marine wildlife of San Lorenzo.', 'La Tortuga de San Lorenzo es un punto fotográfico junto a la playa. Su figura recuerda la riqueza natural del litoral y la importancia de proteger los ecosistemas marinos cercanos.', 'The San Lorenzo Turtle is a photo stop beside the beach. Its form recalls the natural wealth of the coast and the importance of protecting nearby marine ecosystems.', 'https://www.openstreetmap.org/node/8004852220'),
    ('10000000-0000-4000-8000-000000000024'::uuid, 'centros-comerciales', -80.7053223, -0.9663921, 'Avenida 4 de Noviembre, Manta, Manabí', null, null, 'Paseo Shopping Manta', 'Paseo Shopping Manta', 'Centro comercial con tiendas, servicios, restaurantes y entretenimiento.', 'A shopping center with stores, services, restaurants, and entertainment.', 'Paseo Shopping reúne opciones comerciales y de ocio en el sureste urbano de Manta. Puede servir como parada práctica para compras, alimentación y entretenimiento bajo techo.', 'Paseo Shopping brings together retail and leisure options in southeastern Manta. It is a practical stop for shopping, food, and indoor entertainment.', 'https://www.openstreetmap.org/way/1117826245'),
    ('10000000-0000-4000-8000-000000000025'::uuid, 'centros-comerciales', -80.7526932, -0.9455218, 'Vía Barbasquillo, Manta, Manabí', 'https://laquadra.com.ec/', null, 'La Quadra', 'La Quadra', 'Plaza comercial abierta con gastronomía y servicios en Barbasquillo.', 'An open-air commercial plaza with dining and services in Barbasquillo.', 'La Quadra combina locales comerciales, restaurantes y espacios de encuentro en el corredor de Barbasquillo. Su formato abierto la hace apropiada para una visita breve al final de la tarde.', 'La Quadra combines shops, restaurants, and meeting spaces along the Barbasquillo corridor. Its open layout makes it suitable for a short late-afternoon visit.', 'https://www.openstreetmap.org/way/850651512'),
    ('10000000-0000-4000-8000-000000000026'::uuid, 'centros-comerciales', -80.7491223, -0.9458576, 'Vía Barbasquillo, Manta, Manabí', null, null, 'Plaza del Sol', 'Plaza del Sol', 'Conjunto comercial y gastronómico próximo a hoteles y vida nocturna.', 'A retail and dining complex near hotels and nightlife venues.', 'Plaza del Sol forma parte del sector moderno de Barbasquillo. Sus restaurantes y locales permiten combinar una salida gastronómica con otros puntos de interés cercanos.', 'Plaza del Sol is part of modern Barbasquillo. Its restaurants and shops make it easy to combine dining with other nearby points of interest.', 'https://www.openstreetmap.org/way/865796562'),
    ('10000000-0000-4000-8000-000000000027'::uuid, 'hoteles', -80.7325120, -0.9411465, 'Avenida Malecón y Calle 23, Manta, Manabí', null, 4, 'Hotel Oro Verde Manta', 'Oro Verde Manta Hotel', 'Hotel frente al mar próximo a El Murciélago y al centro comercial.', 'A seafront hotel near El Murciélago Beach and the shopping district.', 'Oro Verde Manta se ubica en uno de los corredores turísticos más accesibles de la ciudad. Desde el hotel se llega con facilidad a la playa, el malecón y varios servicios urbanos.', 'Oro Verde Manta stands on one of the city’s most accessible tourism corridors. The beach, boardwalk, and a range of urban services are within easy reach.', 'https://www.openstreetmap.org/way/1433893287'),
    ('10000000-0000-4000-8000-000000000028'::uuid, 'hoteles', -80.7303404, -0.9425469, 'Avenida 7 y Calle 20, Manta, Manabí', null, 3, 'Hotel Balandra', 'Balandra Hotel', 'Alojamiento céntrico cerca del malecón, museos y Playa El Murciélago.', 'Central accommodation near the boardwalk, museums, and El Murciélago Beach.', 'Hotel Balandra ofrece una ubicación conveniente para recorrer a pie parte del frente marítimo. Su entorno conecta con espacios culturales, restaurantes y la principal playa urbana.', 'Balandra Hotel offers a convenient base for exploring part of the waterfront on foot. The surrounding area connects with cultural venues, restaurants, and the main urban beach.', 'https://www.openstreetmap.org/way/1298213572'),
    ('10000000-0000-4000-8000-000000000029'::uuid, 'hoteles', -80.7490143, -0.9444395, 'Vía Barbasquillo, Manta, Manabí', 'https://www.mantahosthotel.com/web/', 4, 'Mantahost Hotel', 'Mantahost Hotel', 'Hotel y centro de convenciones en el corredor turístico de Barbasquillo.', 'A hotel and convention venue on the Barbasquillo tourism corridor.', 'Mantahost es una referencia hotelera de la zona occidental urbana. Su localización permite acceder a restaurantes, plazas comerciales, playas y espacios para eventos.', 'Mantahost is a well-known hotel in western urban Manta. Its location provides access to restaurants, shopping plazas, beaches, and event venues.', 'https://www.openstreetmap.org/node/940960025'),
    ('10000000-0000-4000-8000-000000000030'::uuid, 'hoteles', -80.7496660, -0.9446366, 'Vía Barbasquillo, Manta, Manabí', null, 4, 'Hotel Poseidón', 'Poseidon Hotel', 'Hotel de altura con vistas al litoral de Barbasquillo.', 'A high-rise hotel with views over the Barbasquillo coastline.', 'Hotel Poseidón se encuentra cerca de plazas comerciales y restaurantes del sector Barbasquillo. Su posición elevada ofrece una perspectiva amplia del paisaje urbano y marino.', 'Poseidon Hotel is close to the shopping plazas and restaurants of Barbasquillo. Its elevated position provides broad views of the urban and coastal landscape.', 'https://www.openstreetmap.org/way/1432118709'),
    ('10000000-0000-4000-8000-000000000031'::uuid, 'hoteles', -80.7507423, -0.9457280, 'Avenida Flavio Reyes, Manta, Manabí', null, 4, 'Wyndham Manta', 'Wyndham Manta', 'Hotel y centro de convenciones junto al sector comercial de Barbasquillo.', 'A hotel and convention center beside Barbasquillo’s commercial area.', 'Wyndham Manta se integra a una zona con servicios turísticos, gastronomía y vida nocturna. Es una base práctica para explorar las playas occidentales y el área urbana.', 'Wyndham Manta sits within an area of visitor services, dining, and nightlife. It is a practical base for exploring the western beaches and urban attractions.', 'https://www.openstreetmap.org/way/850651516'),
    ('10000000-0000-4000-8000-000000000032'::uuid, 'restaurantes', -80.7451867, -0.9460512, 'Sector Barbasquillo, Manta, Manabí', null, 4, 'Martinica Manta', 'Martinica Manta', 'Restaurante contemporáneo reconocido en el corredor gastronómico de Barbasquillo.', 'A contemporary restaurant on Barbasquillo’s dining corridor.', 'Martinica forma parte de la oferta gastronómica moderna de Manta. Su ubicación facilita combinar una comida con un recorrido por Barbasquillo, sus plazas y el frente costero.', 'Martinica is part of Manta’s contemporary dining scene. Its location makes it easy to combine a meal with a visit to Barbasquillo, its plazas, and the waterfront.', 'https://www.openstreetmap.org/node/4416774494'),
    ('10000000-0000-4000-8000-000000000033'::uuid, 'restaurantes', -80.7395436, -0.9472309, 'Sector Umiña, Manta, Manabí', null, 3, 'Finisterre', 'Finisterre', 'Restaurante de cocina variada en una zona céntrica de Manta.', 'A varied-cuisine restaurant in a central area of Manta.', 'Finisterre se ubica entre el centro y el corredor de Barbasquillo. Es una alternativa gastronómica cercana a hoteles, comercios y vías principales de la ciudad.', 'Finisterre is located between central Manta and the Barbasquillo corridor. It is a dining option near hotels, shops, and major city routes.', 'https://www.openstreetmap.org/node/4174659125'),
    ('10000000-0000-4000-8000-000000000034'::uuid, 'restaurantes', -80.7391286, -0.9463591, 'Calle 27 y Avenida 30, Manta, Manabí', 'https://www.facebook.com/cevicheriauminaec', 2, 'Cevichería Umiña', 'Umiña Cevichería', 'Cevichería local dedicada a preparaciones de pescado y mariscos.', 'A local cevichería specializing in fish and seafood dishes.', 'Cevichería Umiña representa la cocina marinera cotidiana de Manta. Es una opción para probar ceviches y otras preparaciones vinculadas a la pesca local.', 'Umiña Cevichería represents Manta’s everyday seafood cooking. It is an option for tasting ceviche and other dishes connected with the local fishing tradition.', 'https://www.openstreetmap.org/node/2271784081'),
    ('10000000-0000-4000-8000-000000000035'::uuid, 'restaurantes', -80.7339362, -0.9461236, 'Centro de Manta, Manabí', null, 2, 'Cevichería Flipper #3', 'Flipper Cevichería #3', 'Restaurante popular de ceviches y platos marineros en el área urbana.', 'A popular urban restaurant for ceviche and seafood dishes.', 'Flipper #3 ofrece una parada gastronómica accesible durante un recorrido por el centro. Su especialidad permite acercarse a sabores muy asociados con la identidad culinaria mantense.', 'Flipper #3 offers an accessible food stop during a tour of central Manta. Its specialty introduces visitors to flavors closely associated with the city’s culinary identity.', 'https://www.openstreetmap.org/way/440234134'),
    ('10000000-0000-4000-8000-000000000036'::uuid, 'vida-nocturna', -80.7316387, -0.9444620, 'Zona Rosa, Manta, Manabí', null, 2, 'Adrenalina Discotec', 'Adrenalina Nightclub', 'Discoteca ubicada en el sector de entretenimiento nocturno de Manta.', 'A nightclub in Manta’s evening entertainment district.', 'Adrenalina forma parte de la oferta nocturna próxima a la avenida Flavio Reyes. Conviene verificar horarios y condiciones de ingreso antes de la visita.', 'Adrenalina is part of the nightlife around Flavio Reyes Avenue. Visitors should verify opening hours and entry conditions before going.', 'https://www.openstreetmap.org/node/13195198212'),
    ('10000000-0000-4000-8000-000000000037'::uuid, 'vida-nocturna', -80.7326003, -0.9447315, 'Avenida Flavio Reyes, Manta, Manabí', null, 2, 'Planeta Rosa Karaoke', 'Planeta Rosa Karaoke', 'Karaoke en la zona de bares y restaurantes de Flavio Reyes.', 'A karaoke venue in the bars and restaurants area of Flavio Reyes.', 'Planeta Rosa ofrece una alternativa de entretenimiento nocturno basada en música y canto. Su entorno permite encontrar otros locales a corta distancia.', 'Planeta Rosa offers music-and-singing nightlife in the Flavio Reyes area. Other evening venues are located within a short walk.', 'https://www.openstreetmap.org/node/12111600318'),
    ('10000000-0000-4000-8000-000000000038'::uuid, 'vida-nocturna', -80.7330752, -0.9451063, 'Avenida Flavio Reyes, Manta, Manabí', null, 3, 'Sensation Lounge Bar', 'Sensation Lounge Bar', 'Lounge bar en uno de los principales corredores nocturnos de la ciudad.', 'A lounge bar on one of the city’s main nightlife corridors.', 'Sensation Lounge Bar se encuentra en la avenida Flavio Reyes, cerca de restaurantes y otros bares. Se recomienda confirmar programación, horarios y requisitos de acceso.', 'Sensation Lounge Bar is on Flavio Reyes Avenue near restaurants and other bars. Visitors should confirm events, hours, and entry requirements.', 'https://www.openstreetmap.org/way/1475446369'),
    ('10000000-0000-4000-8000-000000000039'::uuid, 'vida-nocturna', -80.7328745, -0.9449418, 'Zona Rosa, Manta, Manabí', null, 2, 'Bacana Bar', 'Bacana Bar', 'Bar compacto dentro del circuito nocturno cercano a Flavio Reyes.', 'A compact bar within the nightlife circuit near Flavio Reyes.', 'Bacana Bar integra el conjunto de locales de la Zona Rosa de Manta. Su visita puede combinarse con restaurantes del sector, tomando las precauciones habituales de movilidad nocturna.', 'Bacana Bar is part of Manta’s Zona Rosa nightlife cluster. It can be combined with nearby restaurants while following normal precautions for evening travel.', 'https://www.openstreetmap.org/node/13194612056'),
    ('10000000-0000-4000-8000-000000000040'::uuid, 'actividades', -80.8818311, -1.0242643, 'Ligüiqui, Manta, Manabí', null, 0, 'Corrales Marinos de Ligüiqui', 'Ligüiqui Marine Corrals', 'Vestigios arqueológicos costeros asociados a técnicas ancestrales de pesca.', 'Coastal archaeological remains linked to ancestral fishing techniques.', 'Los Corrales Marinos muestran cómo las comunidades aprovecharon las mareas y la forma del litoral para capturar recursos marinos. La visita debe realizarse con respeto por el sitio y las condiciones de marea.', 'The Marine Corrals show how communities used tides and coastal landforms to gather marine resources. Visits should respect the site and account for tidal conditions.', 'https://www.openstreetmap.org/node/12063941542'),
    ('10000000-0000-4000-8000-000000000041'::uuid, 'actividades', -80.8105236, -0.9562113, 'San Mateo, Manta, Manabí', null, 0, 'Centro Cultural Buque Azart', 'Azart Ship Cultural Center', 'Buque convertido en espacio comunitario y cultural junto a San Mateo.', 'A ship converted into a community and cultural venue beside San Mateo.', 'El Buque Azart reutiliza una embarcación como escenario para actividades culturales. Su singular ubicación suma una experiencia diferente al recorrido por San Mateo y su frente marítimo.', 'The Azart Ship reuses a vessel as a setting for cultural activities. Its unusual location adds a different experience to a tour of San Mateo and its waterfront.', 'https://www.openstreetmap.org/way/1531512489'),
    ('10000000-0000-4000-8000-000000000042'::uuid, 'actividades', -80.7298220, -0.9406058, 'Puerto de Manta, Manabí', null, 0, 'Terminal de Cruceros de Manta', 'Manta Cruise Terminal', 'Punto de llegada marítima con servicios e información para visitantes.', 'A maritime arrival point with visitor services and information.', 'La Terminal de Cruceros conecta el puerto con el circuito turístico urbano. Cuando hay operaciones permite observar el movimiento de pasajeros y acceder rápidamente al malecón y al centro.', 'The Cruise Terminal connects the port with the urban tourism circuit. During operations, visitors can observe passenger activity and quickly reach the boardwalk and city center.', 'https://www.openstreetmap.org/way/1116640504'),
    ('10000000-0000-4000-8000-000000000043'::uuid, 'actividades', -80.7539582, -0.9481590, 'Sector Barbasquillo, Manta, Manabí', null, 2, 'Umiña Tennis', 'Umiña Tennis', 'Centro deportivo para actividades de tenis en el sector Barbasquillo.', 'A sports center for tennis activities in the Barbasquillo area.', 'Umiña Tennis amplía las alternativas de actividad física para residentes y visitantes. Se recomienda consultar disponibilidad, reservas y tarifas antes de acudir.', 'Umiña Tennis broadens the physical activity options available to residents and visitors. Availability, reservations, and fees should be checked in advance.', 'https://www.openstreetmap.org/way/1302435187')
), inserted_places as (
  insert into public.places (
    id, category_id, status, location, address, website_url, opening_hours,
    price_level, is_featured, published_at, source_name, source_url, source_checked_at
  )
  select
    pd.id,
    c.id,
    'published'::public.content_status,
    extensions.st_setsrid(extensions.st_point(pd.longitude, pd.latitude), 4326)::extensions.geography,
    pd.address,
    pd.website_url,
    '{}'::jsonb,
    pd.price_level,
    false,
    now(),
    'OpenStreetMap',
    pd.source_url,
    '2026-07-22T00:00:00Z'::timestamptz
  from place_data pd
  join public.categories c on c.slug = pd.category_slug
  on conflict (id) do update set
    category_id = excluded.category_id,
    status = excluded.status,
    location = excluded.location,
    address = excluded.address,
    website_url = excluded.website_url,
    price_level = excluded.price_level,
    source_name = excluded.source_name,
    source_url = excluded.source_url,
    source_checked_at = excluded.source_checked_at,
    updated_at = now()
  returning id
)
insert into public.place_translations (place_id, locale, name, short_description, description)
select pd.id, 'es', pd.name_es, pd.short_es, pd.description_es
from place_data pd
union all
select pd.id, 'en', pd.name_en, pd.short_en, pd.description_en
from place_data pd
on conflict (place_id, locale) do update set
  name = excluded.name,
  short_description = excluded.short_description,
  description = excluded.description;
